language: go
sudo: false

go:
  - 1.11.x

env:
  - CODECOV_TOKEN="ba6b6030-61c4-4729-95e6-f354aca0368e"

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -t -v ./...
  - golint

script:
  - CGO_ENABLED=0
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - export GO111MODULE=off

branches:
  only:
    - master